Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.name = "control_node"
    d.remains_running = true

    # 🔥 acesso ao daemon do host
    d.volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
  end

  config.vm.hostname = "control-node"
end
