Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "almalinux-dood"
    d.remains_running = true
    d.cmd = ["sleep","infinity"]

    d.volumes = [
      "/var/run/docker.sock:/var/run/docker.sock"
    ]
  end
end