Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.name = "app01"
    d.remains_running = true

    # Porta SSH (host:guest)
    d.ports = ["2200:22"]
    # Porta da aplicação
    d.ports << "8080:8080"
  end

  config.vm.hostname = "app01"
end
