Vagrant.configure("2") do |config|

  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.name = "vagrant_lab"
    d.remains_running = true
  end

  config.vm.network "forwarded_port",
    guest: 80,
    host: 8080,
    host_ip: "127.0.0.1"

end



